services:
  node:
    build: .
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
      TASK_QUEUE: ${TASK_QUEUE}
      RESULT_QUEUE: ${RESULT_QUEUE}
      DELAYED_EXCHANGE: ${DELAYED_EXCHANGE}
      PROXY: ${PROXY}
      PROXY_API_URL: ${PROXY_API_URL}
