name: ESLint Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Change directory
      run: cd master/website

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint
